### ISSUE TITLE
[1.16.5] Wardance Server Crash - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#11]
**Context:** I was fighting enemies in the Nether (brutes), with my Phantasmal Blade from IceAndFire mod, doing this, the server crashed and kick all the players during the test from my server. Nothing was sent to the client.

**Here's the Server logs:**
[debug-1.log](https://github.com/Jackiecrazy/WarDance/files/6080705/debug-1.log) **Line 7419**
[2021-03-04-1.log](https://github.com/Jackiecrazy/WarDance/files/6080687/2021-03-04-1.log) **Line 1550**

**Comment by Cixon** [comment]
Additional infomation:

I'm not sure what changed from the last version I was using to this one but, this error occurs to anything that isn't registered to config. At least from what I'm seeing. I got another crash testing a mod out that adds a new arrow type. Shooting it, causes the server to also crash.

**Comment by Jackiecrazy** [comment]
Oh, crap, I forgot to separate the client and server again. That's what happens when you code at 4AM, I guess. So sorry, fix has been uploaded.
