### ISSUE TITLE
[1.16.5] Servercrash Wardance-v0.2.6 - java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#13]
**Context:** I was in the Nether, playing with my modpack, came across another crash, with Wardance.
Debug log mentions a Basalt Giant which is from [Infernal Expansion](https://www.curseforge.com/minecraft/mc-mods/infernal-expansion).

_(removed the wardance mod and don't have issues anymore, I hate I come across these crashes so often lol. why meee?)_

**Here's Your Logs:**
[crash-2021-03-04_22.32.46-server.txt](https://github.com/Jackiecrazy/WarDance/files/6087058/crash-2021-03-04_22.32.46-server.txt)
[debug-2.log](https://github.com/Jackiecrazy/WarDance/files/6087085/debug-2.log) **Line 7765**

**Comment by Cixon** [comment]
Sorry if all these reports annoy you, I should earn a cookie. lol.

**Comment by Jackiecrazy** [comment]
I'm guessing others also have issues, but they don't bother reporting. This crash is partially due to forge's strange default behavior for getting attribute values, and a fix has been uploaded. 🍪
