### ISSUE TITLE
I don't have a answer to this but this is worth the investigation, I think.

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#14]
**Context:** I was just playing with your latest update (v0.2.6.2) on a server environment and I have to say everything seems to be working as it should with no crashes _(yet)_, but, there is one issue that I'm investigating how to reproduce.

**Bug:** My server dips to an unplayable low before being clogged with errors to the console.

I do have a small copy of the error that I grabbed from the console, perhaps you can read it and make something of it.

**Log:**
[ex-log1.log](https://github.com/Jackiecrazy/WarDance/files/6096497/ex-log1.log)

**Comment by Cixon** [comment]
Seems to be some kind of error with wardance requesting a packet update.

**Comment by Jackiecrazy** [comment]
Do you remember what entity you had your crosshair on when this happened?

**Comment by Cixon** [comment]
I do not, I will have to moderate the console log while testing the entities in my personal modpack.
Figured I would plug this ticket in-case you were aware of this issue. I will do further testing.

**Comment by Cixon** [comment]
So I didn't have my crosshair on a mob, nor did anyone else because this was tested on a separate server and different world by myself.

I was able to capture the log again.

Screenshot of my position:
![Screenshot (116)](https://user-images.githubusercontent.com/69068153/110231492-ab323a80-7edd-11eb-982b-138e4a22a2fb.png)

Log:
[ex-log2.log](https://github.com/Jackiecrazy/WarDance/files/6096682/ex-log2.log)

**Comment by Cixon** [comment]
I found the problem. Going to upload video!

**Comment by Cixon** [comment]
Seems to be something to do with dragon corpses.

https://youtu.be/O1rEfUwZQEc

**Comment by Jackiecrazy** [comment]
Gotcha, I also streamlined the request-based stat sync a bit, so the new version should be slightly faster.
