### ISSUE TITLE
[1.16.5] [v0.2.6.2] Totem of Undying is funky!

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#16]
**Suggestion:** If a player/entity dies with Totem of Undying, wounding effect resets and all hearts lost are regained.

As of rn, they just get totem buff with 1 heart.

**Comment by Jackiecrazy** [comment]
oh right, I forgot ToU existed. I'll see if I can make all "death cheating" items/abilities (e.g. doctor who's regeneration) reset stats.

**Comment by Jackiecrazy** [comment]
Looks like totems are indeed supposed to keep you at one heart and give you buffs. I will keep it that way, but allow all death avoiders to reset decay values (wounding/fatigue/burnout). Next update is gonna take a bit while I flesh out the stealth system and rewrite sweeping edge a bit.

**Comment by Jackiecrazy** [comment]
done in 0.3.0!
