### ISSUE TITLE
Crash on hit/attack

### ISSUE THREAD

**Issue by korncob** [Jackiecrazy/WarDance#2]
Forge version : 35.1.37
Minecraft : 1.16.4

This seems to happen when I attack with bare fists regardless of hitting something or not. I'm guessing it's possibly a version compatibility thing? I'm not great at reading these yet, but I hope this helps.

[crash-2021-02-16_20.24.28-server.txt](https://github.com/Jackiecrazy/WarDance/files/5993228/crash-2021-02-16_20.24.28-server.txt)

**Comment by Jackiecrazy** [comment]
Update.

**Comment by Jackiecrazy** [comment]
Assuming this is fixed?
