### ISSUE TITLE
[Compat] With Tetra's modular sword players can always perform sweeping

### ISSUE THREAD

**Issue by No3371** [Jackiecrazy/WarDance#20]
This is is ok if it only deal normal sweeping damage, I'd worry that it's too game breaking if it can always sweeping and deal full damage to all enemies.

**Comment by Jackiecrazy** [comment]
Do the weapons have sweeping edge on them? Also, last I recall, one of the tetra blades gives AoE, are you sure it's not that?

**Comment by No3371** [comment]
No sweeping edge attached, as for "innate sweep" I have to double check, will get back to you if I have the result.

**Comment by Jackiecrazy** [comment]
Any news on this matter?

**Comment by No3371** [comment]
Ah, got some time to test it and realize that sweeping seems built in to all sword blade module of tetra.

However it's not presented as enchant, does that means WD sweeping modification won't apply to any Tetra item?

**Comment by Jackiecrazy** [comment]
That is correct. Sweep will not function (it will, in fact, be suppressed for any item that the code recognizes as a "sword") without sweeping edge, if you have the config option enabled.

**Comment by No3371** [comment]
Kinda wondering how it recognize swords but no matter how... Tetra weapons does not inherit from ItemSword so I guess whatever works :p
