### ISSUE TITLE
[WD 0.3.4] Wrong item entry in default config file, config file always reset

### ISSUE THREAD

**Issue by No3371** [Jackiecrazy/WarDance#22]
The item config entry contains 7 fields:
> byg:pendorite_hoe, 2.1, 1.4, false, 1.4, 2, 1.4, 2

**Comment by Jackiecrazy** [comment]
Oh! I got too paste-happy. I only read the first 6 fields anyway, though, so that can't be why it's resetting. I've never had that problem myself, and it hasn't been reported to me on discord; can you help check if something else causes it?

**Comment by No3371** [comment]
Not quite sure, Yesterday I found my config was reset again (not first time, I thought it's because I edited it when server running, or I made mistake in the config) so I did some regex magic to find that line. Then I pasted back my overwritten config and removed that line and ran the server again, it did not get reset.

I'll keep tabs on it then get back to you, maybe several days later!

**Comment by Jackiecrazy** [comment]
I'm going to be closing this if there's no update.
