### ISSUE TITLE
Random crash while swimming in a boat

### ISSUE THREAD

**Issue by HotSh0wer** [Jackiecrazy/WarDance#23]
No idea what causes it. I looked at the crash report and it says something about "Entity Handler" from wardance. Would appreciate if you can figure out what's the problem. Really sorry to waste your time if it isn't caused by your mod
[crash-2021-05-07_17.10.39-server.txt](https://github.com/Jackiecrazy/WarDance/files/6442203/crash-2021-05-07_17.10.39-server.txt)

**Comment by Jackiecrazy** [comment]
So this one's still around, huh... noted, I'll fix it along with the rest of the stuff for the next version.

**Comment by Jackiecrazy** [comment]
This should be fixed in 0.5.11.
