### ISSUE TITLE
[Crash] [v3.4] Serious world deadlocks when in conjunction with YUNG's Better Strongholds mod

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#24]
**Context:** I was compiling a mods 1 by 1 to test their compatibles with one another for my upcoming modpack. Upon installing better strongholds and initiating the command /locate betterstrongholds:stronghold it displays the location of the structure just fine. It isn't until you teleport to that location where the server AND client crashes. This occurs for both singleplayer and multiplayer.

**BUILDS**
FORGE 36.1.4
[YUNG's Better Strongholds v1.1](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds/files/3300125)
Wardance v3.4

**LOGS**
[crash-2021-05-09_20.03.28-server.txt](https://github.com/Jackiecrazy/WarDance/files/6448828/crash-2021-05-09_20.03.28-server.txt)
[latest.log](https://github.com/Jackiecrazy/WarDance/files/6448829/latest.log) **Line 1166**

**Comment by Jackiecrazy** [comment]
so it's this one again... does the issue persist across reloads?

**Comment by Cixon** [comment]
> 
> 
> so it's this one again... does the issue persist across reloads?

Reloads? If you mean have I tried reloading the world, yes. I cannot use the world anymore because I tp'd to the modded stronghold

**Comment by Cixon** [comment]
I will say, the stronghold mod works fine when Wardance is not present.

**Comment by Jackiecrazy** [comment]
I know exactly what it is and exactly what causes it. I'll have to just remove the sound alert system, I suppose.

**Comment by Cixon** [comment]
> 
> 
> I know exactly what it is and exactly what causes it, but I'm surprised it's so persistent. I'll have to just remove the sound alert system, I suppose.

Understood, sorry if I caused any inconvenience. I'm always the one that bothers you with a lot of bugs to you. XD

**Comment by Cixon** [comment]
fixed in 0.5.11?

**Comment by Cixon** [comment]
confirmed fixed in latest update!
