### ISSUE TITLE
Invulnerability ticks and attack damage problem

### ISSUE THREAD

**Issue by rtxyd** [Jackiecrazy/WarDance#26]
Some day I find this mod remove the 0.5 sec invulnerability time, and I install other mod that is able to increase base attack damage by some way. So there is the problem, it seems I don't need to wait attack cooldown, so I can keep attack the monster to cause tons of damage and I **every damage is at least base-attack-damage**. This situation is regardless with armor, so for monsters, armor become useless. And for player game become very easy.
Can you add a switch in config that is able to turn on the vanilla invulnerability ticks? Or make the damage mechanism more balanced?

**Comment by Jackiecrazy** [comment]
This mod depends on the attack cooldown not existing. You're installing a mod that increases base attack damage, you really should have expected player power to spike massively; even with the hurt timer, faster weapons ultimately benefit more from strength potions anyway. I already modified fists have -1 attack reach and set them as incapable of parrying to compensate for that exact reason. I refuse to rebalance the entire mod (as at least a third of the features rely on consistent damage output) around an arbitrary, antediluvian mechanic that only served as a crutch for pre-1.9 combat, so allow me to refuse.

**Comment by rtxyd** [comment]
Ehmmmm, since I am not a English speaker, I don't get some of your words. I just feel like to tell you my suggestion about balance from my point, but you are the creator, no matter you take the advise or not, the mod will still be good. There are always people appreciate your work. And I have understood your purpose to remove the the invulnerability time, which is reasonable, core of the mod. But I don't get the reason about the base-attack-damage issue, why do you calculate the base damage as bypassing armor, at the situation that the damage time have been removed? "even with the hurt timer, faster weapons ultimately benefit more from strength potions anyway", this original says that you know it's a unbalanced feature even there invulnerability time exists, this is my confuse.

**Comment by Jackiecrazy** [comment]
I don't. Nothing in this mod ignores armor. The high benefit of faster attack speed is counterbalanced by absorption and slow weapons gaining more might per attack, even after factoring in combo.

**Comment by Jackiecrazy** [comment]
哦，国人啊。我并没有让基础伤害获得穿甲能力，而且攻速和穿甲也八竿子打不着边。攻速对伤害有极高加成，但是武器越慢攒的威越多（拳头一次0.1，0.5攻速的武器一次半管），还有专门克制小伤害多段的吸收。

**Comment by rtxyd** [comment]
我这边装了mod之后用scaling health将基础伤害提高到5点，瞎打都能秒怪，每次攻击不用等攻击冷却，跟1.7.10一样的效果，但是每次伤害都是打到肉上的，主要我后面试了空手秒怪，他护甲10几点，我拿钻石剑锤和拿空手锤，因为基础伤害无视护甲，但是钻石剑本身的伤害却会被减免，我还不如用空手锤怪。

**Comment by Jackiecrazy** [comment]
这个问题……你不要用scaling health拉自己的基础攻击不就好了？还有基础攻击是SH自己的设定吗？基础伤害是吃护甲的，空手打僵尸的伤害稍微小于1。还有拳头攻击距离-1哦。

**Comment by rtxyd** [comment]
那个，重点不是scaling health加不加基础伤害的问题，只加这个mod对有护甲的怪物也会是这种效果，所以这是什么情况，基础伤害和武器伤害一个算减伤一个不算减伤，只是scaling health让我发现了这个问题。就算我不加scaling health吧，那你这个问题还是存在，基础伤害还是会穿甲。这个问题的存在肯定会让这个mod在某些情况下平衡性很差。即使没有加其他加基础伤害的mod，原版的力量药水也能加基础伤害，你也提到了，加上没有伤害间隔，那喝完力量药水之后原版怪物就算有护甲是不是都是纸糊的了呢？就，我只是从平衡性和和其他mod的兼容性的角度把这个问题提出来。希望作者改改，既然你不想把伤害间隔加回来，那，至少这个基础伤害算进减伤里合理吧？

**Comment by Jackiecrazy** [comment]
**基础伤害不会穿甲，正常计算减伤**。这个问题我已经解释三次了，会就是其他模组在搞鬼。你翻翻我整个代码库除了斩杀以外哪里会穿甲？我自己用我自己写的模组都没有空手直接刚护甲，因为会被减到可以忽略不计的量。武器伤害是直接加在攻击伤害属性上面的，和空手伤害不是分开计算的，包括力量武器锋利所有的结算都会一次性附加给目标，而这次结算是吃减伤的。攻速对伤害有加成，所以引入威和攻击距离反向平衡：拳头空手距离-1，威的积攒速度和攻速成幂反比。吸收是加在护甲上的，没穿护甲就没有。
说实话，一圈看下来我觉得你是专门来杠的。一直坚持一个客观上根本就不存在的问题，不听别人解释还盛气凌人阴阳怪气。

**Comment by rtxyd** [comment]
我也不纠结了，我真不是来杠的，因为我所有的问题都是基于基础伤害会穿甲来说的，如果确实不是这个mod引起的，的确有点强人所难了，这点我先道个歉。应该是我之前测试不严谨的问题。我再去测一下。。

**Comment by rtxyd** [comment]
我之前是在创造模式下测的，这次我生存创造都试了一下。**结果是我的问题。**
基础伤害会穿甲的这个说法似乎是因为连击加伤的问题和连续攻击击倒后护甲降低了，让我感觉打起来像穿甲伤害，而且创造模式下打怪伤害会高很多，生存模式用拳头撸伤害大部分被减免了。
浪费了你的时间，实在很抱歉。那我再提个建议好了，希望加强一下投掷武器和弓箭类武器。

**Comment by Jackiecrazy** [comment]
忘记说了，我在debug.log里面记载了所有伤害，可以查看伤害来源、造成的原伤害和被所有其他效果减免或增加后的最终伤害。至于投掷和弓箭类武器，其他模组好像经常有加强的样子。之后会加一个投掷武器的技能，更新御灵以后还要追加飃石、连弩、火铳、飞镖等远程武器选项。整体机制偏近战，而且远程攻击有绝对的距离优势，所以远程一般会设计成偏辅助向的东西，例如debuff的毒雾箭、造成混乱的火鼠、打断吟唱的飞蝗石、吸引注意力的忍者星云云。

**Comment by rtxyd** [comment]
感谢作者回复了那么多。我的问题也解决了，还是鲁莽了。下次一定玩懂了再反馈。
