### ISSUE TITLE
1.16.5 Crash on Launch

### ISSUE THREAD

**Issue by trafoziya** [Jackiecrazy/WarDance#28]
Hi, I created a mod pack that contains around 45 mods.
It works completely fine until I add Project: War Dance. When I add it, my game crashes on launch, and it works completely fine again when I remove P:WD.

Here is the crash report file.
[crash-2021-06-13_21.58.29-client.txt](https://github.com/Jackiecrazy/WarDance/files/6644481/crash-2021-06-13_21.58.29-client.txt)

**Comment by Jackiecrazy** [comment]
This mod is not compatible with Off Hand Combat.

**Comment by trafoziya** [comment]
> This mod is not compatible with Off Hand Combat.

Can you mention this in CurseForge page or readme.txt, so people like me does not open new issues about that.

**Comment by Jackiecrazy** [comment]
Huh, I thought I marked it as incompatible. I'll check.
