### ISSUE TITLE
Dedicated Server Crash

### ISSUE THREAD

**Issue by trafoziya** [Jackiecrazy/WarDance#29]
Hi, I am using Mohist for my dedicated modded rpg server and it crashes when I launch it. Crash report says it is because of P:WD, which you can see below, so I think it is more of a mod side bug. I can open an issue to Mohist if it is not.

**Comment by Jackiecrazy** [comment]
The crash log is not attached. Are you using off hand combat? The two mods are incompatible.

**Comment by trafoziya** [comment]
Oh sorry, I wrote the message but when I search for the crash report, I couldn't find it. I think Mohist didn't create a crash report because server does not even start when I use P:WD. But I added a CONSOLE log which you can see "wardance" below.
[latest.log](https://github.com/Jackiecrazy/WarDance/files/6662248/latest.log)

**Comment by Jackiecrazy** [comment]
Curious, someone is eliminating resetting the attack timer. I'm not sure which mod it could be, though; would you mind helping out by figuring out which it is?

**Comment by trafoziya** [comment]
> Curious, someone is eliminating resetting the attack timer. I'm not sure which mod it could be, though; would you mind helping out by figuring out which it is?

It works completely fine on singleplayer though.

**Comment by trafoziya** [comment]
But, just to confirm, here is me trying to launch my server ONLY with P:WD. It still crashes at launch and doesn't even create a crash report file. My console log file is below:
[latest.log](https://github.com/Jackiecrazy/WarDance/files/6666159/latest.log)

**Comment by Jackiecrazy** [comment]
Curious, I can launch my test server just fine. Must be Mohist doing something again then, I'll see what I can do about it. Flat out disabling the mixin might disable skills and sweeping, and all weapons might deal virtually no posture damage. I can't tell because I don't run a Mohist server.

**Comment by trafoziya** [comment]
> Curious, I can launch my test server just fine. Must be Mohist doing something again then, I'll see what I can do about it. Flat out disabling the mixin might disable skills and sweeping, and all weapons might deal virtually no posture damage. I can't tell because I don't run a Mohist server.

I was using 1.16.5 version, and Build 646, maybe its something that they fixed after the build I used

**Comment by Jackiecrazy** [comment]
Mohist makes quite a few changes to vanilla code, which will break many mods that expect certain pieces of vanilla code to look a certain way. This will be fixed next update.

**Comment by trafoziya** [comment]
> Mohist makes quite a few changes to vanilla code. There probably is a very good reason they're doing it, but it will break many mods that expect certain pieces of vanilla code to look a certain way. This will be fixed by next update.

Did you open an issue? Should I?

**Comment by Jackiecrazy** [comment]
No need, I fixed it on my side. The mixin was cleaner, but there's another way to skin this cat.

**Comment by trafoziya** [comment]
> No need, I fixed it on my side. The mixin was cleaner, but there's another way to skin this cat.

When is the update? Can you at least give me a fixed current version if you are not gonna publish it soon?

**Comment by Jackiecrazy** [comment]
My discord has beta releases.

**Comment by trafoziya** [comment]
> My discord has beta releases.

I tried but couldn't find your discord, can you add a link to curseforge page or somewhere else

**Comment by Jackiecrazy** [comment]
It is written on the mod page. Sometimes I wonder how many people actually read the entire thing, considering how disproportionately long it is compared to the descriptions of other mods. [Here.](https://discord.gg/wZTrp53)

**Comment by Jackiecrazy** [comment]
This has been fixed in the beta.
