### ISSUE TITLE
When the value of the shield is gone, my game crashes (the green one)

### ISSUE THREAD

**Issue by ainlzj** [Jackiecrazy/WarDance#3]
When the value of the shield is gone, my game crashes
(the green one)

[crash-2021-02-20_09.29.54-client.txt](https://github.com/Jackiecrazy/WarDance/files/6013903/crash-2021-02-20_09.29.54-client.txt)

**Comment by Jackiecrazy** [comment]
Try without optifine first. I'm not confident I can fix an issue if it pertains to optifine.

**Comment by ainlzj** [comment]
I found the reason. The incompatibility with EpicFight

**Comment by Jackiecrazy** [comment]
I found the reason too. It has been fixed from my end. A fix will be uploaded soon.
