### ISSUE TITLE
Crash when an item is dropped into the world. [Loot Beams Compat?]

### ISSUE THREAD

**Issue by ClockwerkKaiser** [Jackiecrazy/WarDance#33]
I'm experiencing a crash using wardance beta version "0.6.35-hotfix" build from the discord. 

Steps to reproduce: 
1. Break a block or throw an item into the world.

That's it. 

Here is the crashlog: https://gist.github.com/ClockwerkKaiser/b4cdce17c12c3a75084fad3025f67eef

This does not happen in the base beta version 0.6.35 build.

**Comment by Jackiecrazy** [comment]
Fixed.
