### ISSUE TITLE
Crash on game startup

### ISSUE THREAD

**Issue by realnot4ound** [Jackiecrazy/WarDance#35]
A sudden crash seconds after loading the game. Unfortunately, the game somehow didn't gave a crash-report. The log is all I had regarding this problem. It's fixed when Project Wardance is removed. 

The Log:
[latest.log](https://github.com/Jackiecrazy/WarDance/files/7043040/latest.log)

**Comment by Jackiecrazy** [comment]
The log you gave me indicates a working game and no trace of PWD. Did you post the log as it appeared after removing the mod by accident?

**Comment by realnot4ound** [comment]
Yeah, I think so.... sorry. However the problem seems to have been fixed after the hotfix update. 🤷‍♂️ Guess it works now. Thanks!
