### ISSUE TITLE
关于战舞计划的一些建议

### ISSUE THREAD

**Issue by ShuangZhu929** [Jackiecrazy/WarDance#36]
一：感觉可以把技能做成快捷键，比如Ctrl+1使用技能一，Ctrl+2使用技能二等等。二：技能建议可以带的主动技能和被动技能变少一点，比如主动4个，被动两个，不然打起架来太麻烦了，也有更多选择性。三：斩杀技能建议削弱一下，打起boss有点没挑战性了。四：招架条能改成生命值的75%左右，我希望打boss时也可以打翻（300血的火龙叫我打半天也弄不倒，他啃我就摔太难受了QWQ）。这个mod战斗机制做的是真的好，如果模组能慢慢改良，那肯定能火，期待期待

**Comment by ShuangZhu929** [comment]
还有，作者大大，能不能把招架那红条改成非战斗状态时回复？对于我这种永夜生存的玩家太不友好了（一打就摔，比碰瓷老头还能摔）

**Comment by Jackiecrazy** [comment]
1. 这个可以加，同时有快捷键和施法轮盘可以根据个人喜好使用（我习惯施法轮盘）。
2. 这个需要认真考虑一下。当前的技能是根据拥有8个主动4个被动设计的，如果减少技能槽的话可能会需要缝合一些现有的技能。
3. 斩杀是专门无脑高血量目标设计的，一个只是血厚的boss也没什么意义。我是按照只狼的方式设计的这两个技能，也许不是很契合MC。具体是哪些boss变得没有挑战性？
4. 最大架势是按照生物的长宽高自动生成的。可以在设置文档里面手动调整。
5. 红条可以通过冥想（又名战吼）的所有变体清零，有五分钟CD时间。我个人只用冥想回红条。

**Comment by ShuangZhu929** [comment]
战斗模式左手和一些枪械冲突了，会多一只手，可以改成当副手没有装备时，隐藏一下

**Comment by Jackiecrazy** [comment]
副手会显示的原因是战斗模式下可以用副手空A，需要某种视觉提醒。拿枪的时候副手也可以拿其他东西吧？一般这些东西的渲染会被覆盖吗？

**Comment by ShuangZhu929** [comment]
w+Shift的游泳动画可以去掉，像双D键的动画就好，不然人物鬼畜有点那啥

**Comment by ShuangZhu929** [comment]
像冰火传说的，bi的一下子300血秒了

**Comment by ShuangZhu929** [comment]
像冰火传说的，bi的一下子300血秒了

**Comment by ShuangZhu929** [comment]
额外植物学的空之律者boss血量变化时攻击方式也会变化，秒了就不太好

**Comment by ShuangZhu929** [comment]
如果行的话，还是建议双击D的动画，攀爬一方块的空间模组上已经有Personality（https://www.mcmod.cn/class/3610.html），这样的话会有更好的动作视角。技能的数值如果可以的话可以做一个配置文件，只需要整合包的作者自行平配置，也可以方便以后不用平衡技能

**Comment by ShuangZhu929** [comment]
如果行的话，还是建议双击D的动画，攀爬一方块的空间模组已经有了https://www.mcmod.cn/class/3610.html  这样的话会有更好的动作视角。 技能的数值如果可以的话可以做一个配置文件，只需要整合包的作者自行平配置，也可以方便以后不用平衡技能

**Comment by ShuangZhu929** [comment]
配置技能数值确实是太耗费时间了，也许是不该考虑的，关于闪避的画面，我在第三人称与越肩视角时产生的鬼畜画面。第一人称过进的距时穿过实体和视角的偏差都会产生不好的战斗体验（跳入僵尸群），我更倾向于把闪避系统做成MOD Elenai Dodge 2 可以轻按Shift或其他按键来闪避，有实体碰撞，就位移一段距离就可以（我更倾向于向战斗性）。在击倒时也能闪避，也是有意设置的吗？

**Comment by ShuangZhu929** [comment]
我对战舞计划下一个版本的建议，希望能够采纳：一，设置技能的按键。二，可以分类技能栏为被动和主动，并且减少一下技能栏（如果真的有手速快，还能精确使用8个技能的，或许可配置技能数量是个好选择）。三，闪避方面建议我上述的修改，(对于洞穴和森林地形，得按Shift+R键再双击W和按Shift+w真的很麻烦，并且攀爬时高一格的地形也无法穿过，我来一发RPG或者直接破坏会更方便）。如果真的能如此更新，那我可以像拔刀剑一样流畅的打出一连串连击，这真的会很nice

**Comment by ShuangZhu929** [comment]
我认为战舞计划这个mod很有前景，战斗机制会很契合MC。它兼容性，平衡性（我也加了特殊AI和怪物增强还有big brain，跟一个近战骷髅打的有来有回），打击感和战斗技巧方面也很nice。以后我觉得可以确实向pvp发展，对于打击，技能的视觉效果可以考虑考虑等等，后面模组真的完善了，他确确实实可以影响到PVP，PVE（职业配合）服务器和整合包作者们，扩展的技能或许可以给制作技能与魔法的作者给予一个模板。总之，这是一款很少见的对MC战斗机制更改的好模组，它的前景不是一般的大，我真的很喜欢战舞计划，希望作者您能越做越好，如果有内测的版本，请务必通知我

**Comment by ShuangZhu929** [comment]
配置技能数值确实是太耗费时间了，也许是不该考虑的，关于闪避的画面，我在第三人称与越肩视角时产生的鬼畜画面。第一人称过进的距时穿过实体和视角的偏差都会产生不好的战斗体验（跳入僵尸群），我更倾向于把闪避系统做成MOD Elenai Dodge 2 可以轻按Shift或其他按键来闪避，有实体碰撞，就位移一段距离就可以（我更倾向于向战斗性，可以拉进距离与闪避就够了）。在击倒时也能闪避，也是有意设置的吗？

**Comment by Jackiecrazy** [comment]
我和Elenai已经有特地联动，安装后我的闪避会被关掉。击倒后可以闪避是刻意为之。技能栏的确是分成被动和主动的，下面四个槽是专门放被动的。按一下技能栏然后往大致方向拉一下鼠标就可以丢技能了，前面也说过所有的技能都是以八个技能槽为前提设计的。砍技能槽这个我会慎重考虑。我不太擅长渲染，实装完所有战舞计划本体的技能（御灵会增加更多玄幻主题的技能）后会尽量增加额外的视觉效果。非常感谢你的支持，我在暂时放置战舞计划，开发“武打圆圈”：一个为生物设置技能组（大约就是兼容性极高的epic fight）、修改部分玩家动作增加普攻前后摇、并为生物增加包围AI的模组，相信发布后也能增加PVP和PVE的趣味性。拔刀剑是按照鬼泣设计的，玩家行动速度整体高于敌人；战舞计划和武打圆圈的设计灵感来源于只狼和黑魂，所以玩家和敌人的行动频率会保持相近。最终期望是既可以用轻武器玩高机动性连招也可以用重兵器最大化打击感（MC本身偏袒高攻速，斧头和剑受到同等锋利和力量加成下增加的DPS是不同的，战舞计划也通过引入吸收和威平衡低攻速武器）。所有内测版本均会在Discord发布。

**Comment by Jackiecrazy** [comment]
有不少人也认为技能槽应该被调整为4主动2被动。如果要这样改的话，要不要轻微加强一下飞踢这一类的物理技能，或者移除每种技能只能装备一个变体的限制？对当前技能平衡有没有什么比较大的不满？（除了两个斩杀一定得砍，扫堂腿太弱这两个必须得调整的）

**Comment by ShuangZhu929** [comment]
我是想技能各个独立，分为主动与被动就最佳。技能方面向三类职业修改，是重武器（“武打圆圈“后面真会不会有双手武器？），可以与黑魂大刀一般，较高前摇与攻击冷却，造成较高额的破甲伤害，或许击倒（克制盾牌）；轻武器的双刀流，有连续打击性，且灵活性高；有防御类，盾牌对抛射物的反射确实很好，长按盾你觉得能不能改成减少收击时减少招架值的损失？飞踢确实太那啥了，我附魔了横扫之刃可以完全替代它，改为加大下3次攻击攻击范围增加到180°左右且为半径为1.5格左右并且按冷却计算如何？威需要连续攻击才会增长，感觉对于精确，冷却较慢的武器是不友好的，我觉得整合进灵会比较好。我觉得战舞计划他可以作为一个模板，供其他mod的武器与技能扩展，并且不会与太大的改动。您的下一款“武打圆圈”可以的话，整合战舞计划也是个好选择。

**Comment by Jackiecrazy** [comment]
冷却较慢的武器获得的威是呈几何倍数增长的，特别慢的武器中一次就可以加差不多一格。[这是每次攻击获得的威和每秒获得的威的一个图表](https://www.desmos.com/calculator/wlm5lu2wcd)，可以看出假设每次都能命中的话0.5攻速的武器为最优解。我不太明白什么是各个技能独立，是说去除变体限制或是变体系统吗？双手武器的确是有的，详情请参考御灵的偃月刀和绳标。战舞计划的确是作为一个模板存在，其实就是剥离并优化御灵的战斗系统后的成果；御灵将以武打圆圈和战舞计划作为前置。我设计技能的时候没有刻意按照某个使用手段设计，因为我想尽量使原版MC所有的机制都能有自己的一席之地。一开始的时候是根据[战斗的五大要素](https://omegathorion.wordpress.com/2013/09/02/game-design-the-relationship-between-weapon-and-wielder/)（分别为力量、防御、速度、节奏、距离）设计变体的，较近期引入的技能里面也在尝试加入幸运、药水、DoT等其他现有的机制。直接制定职业有一定的限制玩家想象力的嫌疑，例如现有的打凤牢龙+蛇毒咒，或者掠影+深藏不露+窒息这种combo很难归类于三种职业中。一开始直接移除了长按盾牌的能力，现在的效果是重置架势冷却然后无事发生。虽然长按盾牌的概念和我的剑术本能相反，但也许需要其他平衡手段。有很多人向我提起过冷却条满才能攻击这个建议。生物的招架概率可以通过设置修改，默认为30%概率用武器招架和90%概率用盾牌招架，也可以设置一些生物能够空手招架或者完全无法招架。自动招架的确对远程单位不太友好，但我真的被古代战争满屏幕的弓兵射怕了……之前还在discord上因为这个辩论了三四天，最后结果是把所有的盾牌削了一大圈。只是从招架上来看的话，目前自动招架抛射物的效率没有比用长按盾牌高多少，而且招架也会自动无视穿透付魔的弩箭，所以大致效果只是战士怼弓箭手不用带痛苦面具而已。

武打圆圈也会为武器增加技能组，装备后会使玩家也拥有一系列拥有前后摇的攻击，参考黑魂和死亡细胞的连招。

利益相关：个人偏好双拳套擒拿，我的主要反馈来源分别偏好二刀流和双手剑。

**Comment by Jackiecrazy** [comment]
大致明白了。就是说不要全是强化普攻类技能，多加一些喝彩和诅咒这样的增减益效果和一些远程技能是吧？下一次更新~~猴年马月~~有一些这样的技能：丢地面上的小东西骗招架的投石、牺牲一只手的功能换来伤害和机动性的双酬佣兵（被动）和武器投掷（主动）、闪避类防御被动铁蒺藜、强化自身或弱化目标的灵力图腾等。战舞计划作为模板，其实我也不太想加入过多在特定世界观里会OOC的技能。有可能会把所有非物理技能丢进一个独立的扩展模组。技能设计上我也有参考[DCSS](crawl.chaosforge.org/)，散魔蚀魂石化三个诅咒变体和隐蔽系统的分心状态都是借鉴来的。这个游戏有一些实用又不无脑的法术（使墙角结冰攻击墙边的敌人、将毒气点燃、加速尸体腐坏制造瘴气、暂时变成一只九头蛇），有时间可以看一看。

**Comment by ShuangZhu929** [comment]
不应该说是职业化，觉得技能可以适配现在近战中任何武器。像MOBA游戏里，有一些快乐男孩，专门被一些带着恶心人的装备来教育（我想，我可以搭配成盾之勇者，拿着盾有着强力的击退，还有恶心人的减速和减攻速，还带着真伤），那会很开启史蒂夫的脑洞

**Comment by ShuangZhu929** [comment]
关于威，他可以作为一种高效益的技能，我是想要它适配现在的武器，用来在合适的时候扭转战局

**Comment by Jackiecrazy** [comment]
的确如此。威鼓励的是憋大招，灵则类似行动点限制玩家爆发力。我有在考虑独臂拳王或者盾之勇者这一类限制构筑换来高收益的技能。一大隐患是容易极度两极分化，不是十零开就是零十开。斩杀的威要求调到了3，造成20%已损失生命的伤害；重击移除了威要求；飞踢增加了显著的击退效果，扫堂腿范围增加到360度；索命要求7威以上但消耗的是7灵，继承了斩杀的CD，造成20%当前生命的伤害。
