### ISSUE TITLE
[1.16.5] [wardance v0.7.1-hotfix-3] Servercrash - Can't find attribute wardance:max_spirit

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#39]
**Context:** I was in spectator mode roaming around the underground in the overworld where i spotted a the iron guy from mowzies mob's and upon approaching it, the server crashed.

**Crash log:**
[crash-2021-10-30_03.36.44-server.txt](https://github.com/Jackiecrazy/WarDance/files/7445761/crash-2021-10-30_03.36.44-server.txt)

**Log (line 16,123):**
[latest.log](https://github.com/Jackiecrazy/WarDance/files/7445764/latest.log)

**Comment by Cixon** [comment]
this issue applies to other mobs from different mobs as well from my testing.

**Comment by Jackiecrazy** [comment]
I note you are using the first hotfix; has this been fixed as of hotfix-3?

**Comment by Cixon** [comment]
i believe issue is fixed in v0.7.3, haven't fully tested all yet
