### ISSUE TITLE
[1.16.5/Latest mod] Client Startup failed

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#4]
**Context:** I'm pairing this mod with a mod-pack I personally use but I know for a fact the all the mods work because I never had issues on startup, it was only when I decided to pair War Dance with my pack that I couldn't get things to load.

It mentions something about;
_java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/EntityAttributeCreationEvent_

### Logs: 
[latest.log](https://github.com/Jackiecrazy/WarDance/files/6018413/latest.log) **Line 79**
[debug.log](https://github.com/Jackiecrazy/WarDance/files/6018414/debug.log) **Line 1910**

**Comment by Cixon** [comment]
My forge version is **1.16.5 / 36.0.21**

**Comment by Jackiecrazy** [comment]
Update to 36.0.42 if you can. I'm not sure why that snippet of test code was included in the release, but it'll be gone by next update.

**Comment by Cixon** [comment]
I'll test that out right now! :)

**Comment by Cixon** [comment]
updating to 36.0.42 fixed the issue. thanks!
