### ISSUE TITLE
配置添加请求

### ISSUE THREAD

**Issue by XiFengXF** [Jackiecrazy/WarDance#45]
1:我希望添加配置以取消技能，连击，灵与威。相比于技能，我更想要平衡与战斗机制。
2配置伤，倦，衰的百分比下限，过度的debuff让我感觉不佳
3联动elenai dodge 1 ，添加架势消耗，我觉得可以很好解决现在的闪避问题，并且我不喜欢elenai dodge 2 HUD与添加的物品和护甲限制。
4联动Auto Attack，让左手也能自动攻击，可以解决高攻速的武器DPS无法真正发挥与手残人士的悲催。
5是否可以通过判断是否为空手来提供左手显示，我认为这是解决多一只手的最好办法
希望更新方面：
 · 增加第一人称招架时物品动画，音效
 · 增加持盾被攻击时架势消耗，如果可以，请求修改持盾时速度仅有正常时的50%
Auto Attack：https://github.com/Tfarcenim/AutoAttack

**Comment by Jackiecrazy** [comment]
1. gamerule lockWarSkills true 就没有技能了。
2. 可以关掉的。
3. 这个可以在elenai dodge 2 本身关掉。
4. 也许会考虑，联动工作量很大的……
5. 的确有判定是不是空手。
6. 持盾会重置架势冷却且不会重置连击冷却，至于需不需要更重的代价暂时未知。
7. 配置越多越好调整但也越难上手，需要取舍核心机制的可调整性。

**Comment by XiFengXF** [comment]
2其实伤，倦，衰我认为挺好，但是希望不用过多负面效果而影响游玩性
5判定右手是否为空手来提供左手显示，因为总与双持的武器，工具冲突。一般而言，在添加地下城武器下，我是不会一个单手剑与一个空手打怪的
·通过动画或与敌方怪物不同的招架音效来提示，能更好的提示玩家，而不是与怪物招架混淆
·持盾招架衰减是解决部分ai提升后会持盾的怪物基本打不了的问题。在游戏里，一旦遇到，你会打十几次仍不掉血全免伤的鬼玩意
史诗级战斗模拟是因为硬直才把我劝退的，黑魂不需要像mc那样晚上面对一堆怪物，对于mc而言，太过于笨重。这个战斗机制可圈可点的主要是架势，躺地，伤，倦，衰，以及没有烦人的硬直，我认为该mod更符合mc战斗机制的革新

**Comment by Jackiecrazy** [comment]
作为地下城武器的开发之一……这是刻意设计的（双持和回响付魔出于我之手）；作为学过剑术的人，即使是双手剑也有腾出一只手擒拿的招式。总之我会加一套双手武器设置，手持这些武器的时候会关掉副手。AI提升这种可以通过重击和斧头类武器解决。硬直是很烦，我还在尝试处理缺少前摇的战斗系统下的防御方式，所以暂时是自动招架。
