### ISSUE TITLE
取消技能设置在全局覆盖

### ISSUE THREAD

**Issue by XiFengXF** [Jackiecrazy/WarDance#46]
因为要做整合包，希望取消技能这个设置可以在配置文件中全局覆盖，希望能添加一下，或者能改诉我有其他全局覆盖的办法吗？非常感谢

**Comment by Jackiecrazy** [comment]
需要创造数据包，在load.json中取消技能。Openloader可以默认加载数据包以使其全局覆盖。有一点繁琐，但是每个技能加独立的开关更繁琐……
/gamerule lockWarSkills true后所有技能都需要指令解锁，可以默认为全部移除。

**Comment by XiFengXF** [comment]
容我再个问题，玩家招架方面可以用什么手段取消？在模组的潜行方面，当不穿装备，无效果，走到怪物面前，直到碰撞才发觉玩家，有什么办法可以修改怪物这么眼瞎？

**Comment by Jackiecrazy** [comment]
招架有设置可以改成有时间要求，改成人类不可能做到的数值（比如1tick）就差不多了。潜行的系统比较复杂，根据生物的视野、声音、光亮等级、幸运、速度等要素决定。生物自己拥有额外设定，比如僵尸默认是聋的、亡灵普遍可以夜视、上古守卫者拥有全知之眼，所以知道生物的特性可以更好的潜行。这些生物特定的特性可以在stealth.toml 里面更改。还有两个设定default mob horizontal FoV 和 default mob vertical FoV 可以修改默认生物视野，改成360就不会那么瞎了。armor stealth debuff，字面意思，可以增加每点护甲为怪物增加的视野。alert volume multiplier可以使玩家所有的声音惊动更远的生物，60以下的数字都可以试一试。还可以用指令修改默认的隐蔽属性，改成20以下的数字都会使玩家更加明显（下限0）。最后还可以直接关掉整个潜行系统……

**Comment by XiFengXF** [comment]
好吧，非常感谢您的帮助。顺便提一嘴，我想到一种方法，修改原版盾牌的前摇，可以改变持盾时的速度，并且添加盾牌防御时也收到架势攻击，但是可以减免，以此来代替招架防御系统，也能更好兼容其他mod的盾牌。因为招架的弊端是可以防御任何伤害的攻击，在一方面上是不平衡的。这个模组确实挺有意思，潜行系统甚至优化了我的性能......其实我认为更需要修改的战斗方面的内容，优点主要也是在此。技能其实放在单独或一类型的武器上搭配或许更好

**Comment by XiFengXF** [comment]
修仙的最后推荐几个mod模板看看是否能为目前战舞计划的一些问题提供一些帮助
·https://www.curseforge.com/minecraft/mc-mods/twohanded 定义双手标签
·https://www.curseforge.com/minecraft/mc-mods/off-hand-combat 这个的副手可以让更多其他mod的装备使用
·https://www.curseforge.com/minecraft/mc-mods/responsive-shields护盾前摇修改
·https://www.curseforge.com/minecraft/mc-mods/elenai-dodge 也许在配置文件中添加这种类型的闪避使用，其实其他玩家也是多习惯于这个

**Comment by Jackiecrazy** [comment]
招架的设计是故意为之。一般来说招架是用来奖励学习攻击规律的（只狼、死亡细胞、塞尔达），但是MC并没有什么可以学习的前后摇，所以最后优化掉了手动招架。不使用原版盾牌的原因是设计宗旨偏向高机动性战斗，过度依赖盾牌会亏节奏，还有大部分剑术都有不依靠盾牌的招架动作。我的副手攻击系统其实和off hand combat是一模一样的，使用这个物品注册系统是为了修改攻击架势伤害和开放一些比较骚的操作（比如可以用火把平a，用魔法书招架）。战舞计划是和elenai dodge 2有联动的。
