### ISSUE TITLE
1.16.5] Feature/compat: Better Epic Fight mod integration (auto switch detection)

### ISSUE THREAD

**Issue by SteamDoge9000** [Jackiecrazy/WarDance#47]
this mod looks promising, but one thing that's acting as an inconvenience is that it is not engaging with the epic fight in terms of coming alive when the auto-switch option in EFM is enabled (this is a list that caused the mod to enter its Combat Mode when an item from the list is detected) this feature is supposed to allow a quick and easy transmission between combat and mining mode (regular) effectively without the push of a button but it seems that war dance is not doing this

Recommendation: add a config option within the compt menu to determine if the mods own combat mode system is activated when the player enters EFM combat mode, and exit out of it if the mod detects the player is no longer in combat mode (mining mode)

hope you find this a good idea, I think it would be and make things easier (it would also save the keybind if the user presses the EFM keybind to enter its combat mode and your mods combat mode without having to push 2 buttons to have both on and off.

**Comment by Jackiecrazy** [comment]
How does PWD play with EFM? I don't really want to add compat because it's an fairly minor issue that doesn't really warrant a config option, whose cost of adding is yet another build dependency for a mod with a completely different design direction...

**Comment by SteamDoge9000** [comment]
It did say there was an out-of-the-box compatibility with it so I assumed

**Comment by SteamDoge9000** [comment]
I wasn't planning on it to be in dependency dependency I was thinking more of an optional dependency like a compat teacher

**Comment by SteamDoge9000** [comment]
I do believe that by adding this optional dependency compatible feature is that it'll make the gameplay more smooth as your combat system will be initiated if detects _EFM_ Switching into it it's on combat mode, the config option is the weather configure this features enabled or disabled

**Comment by Jackiecrazy** [comment]
Yes, but an optional dependency has to be loaded in my workspace for me to add compatibility, and will have to be loaded for all eternity afterwards to make sure the mod properly compiles. Out-of-the-box compatibility means EFM items are registered as parry capable. We take combat in completely different directions; PWD adapts external mechanics to accommodate Minecraft, while EFM adapts Minecraft to accommodate external mechanics. While this is not overly difficult to add, I don't want to establish a precedent for explicit EFM compat in any shape or form, as its existence will require me to dramatically alter all manners of design. This is probably not a very satisfactory answer, and I apologize for that. There really isn't much downside to leaving combat mode on all the time, to be honest, beyond accidentally punching stuff you want to interact with, but that's a non-issue if you turn dual-wielding mechanics off (which is advisable, as it presents visual and mechanical issues with EFM).

**Comment by SteamDoge9000** [comment]
So if I'm getting a straight there is no easy or logical way to detect the player entering combat mode in EFM without making some external complicated internal changes to the mothers trying to access them itself

**Comment by SteamDoge9000** [comment]
What an alternative get more optional way is to be for another source mod/add-on that could be worked on hooks provided by the main mod to add optional integration into it?

Would it be possible to do with that method or would it just be more complicated than doing it in the mod itself?



And I can understand that you don't want to; besides the Dev has undergone radio silence currently in the mod is still buggy, in terms that I can break other moms in unexpected ways

you can either try to integrated it to auto activate when a certain item is held possibly by if possible pulling from the config values from the epic fight mod stored auto switch values (this one sure that any weapon that is possibly held that is registered within the auto switching section of epic fight mode would indeed auto activate the hud when an item in that specific list is held)

2. Integrate the mod method from detecting whether combat mode is enabled or disabled to determine the HUD overlay and have a controlled by a master override via config to determine whether this function is active or not

3. Implement a config option that would disable key features that would cause the HUD to stay on under all circumstances and only be disabled via the use of a key bind (this would be a minimalist solution because the HUD would stay on until someone dies, It would then reset and the display would disable and would require The price of a key binds again to reenable it)

**Comment by SteamDoge9000** [comment]
on another side note, it would be nice if their was an option to disable the staggered bar showing up for a brief second whenever you press SHIFt, its quite annoying for it to just pop up randomly whenever you sneak

**Comment by Jackiecrazy** [comment]
I know how to implement it, trust me; I've been writing code for 7 years. It's not the lack of ability, but rather the lack of will. Detecting anything from epic fight requires it to be loaded, which means I have to add it as a dependency _while_ coding, and I don't want to do that because it changes literally everything, requiring me to work around it while testing. As for the other options, they are unnecessarily complicated. More config is not better, despite what people might say; it detracts from overall readability if the options are superfluous. The posture bar shows up briefly because your size changes upon sneaking, lowering your max posture slightly. This will also happen when swimming or changing your size with Pehkui. As this is useful information, I do not believe it should be suppressed. Making max posture not be reduced by sneaking, and sneaking alone, is a strange casing and requires messy reversion of size calculations that immediately break other sneaking entities.

**Comment by SteamDoge9000** [comment]
I see. you have a fair point. I guess some third-party add-on would have to do this for it to happen. I was recommending three because I thought it would be simple to do (because it would just basically keep PWD's combat mode on, even after death). and I will not argue about the idea of config values, while I think otherly of it, you are correct in how more config options can be a bad thing; my recommendations on using it was me looking at "if the user does, not like this sort of thing" and giving them an option to customize it. I'm not saying you're wrong with your belief on config stuff, I'm saying that you do have a valid point (which is why I'm thankful now configured re-implements the in-game config adjustment system). 

as for the shift with the posture, that Is interesting. though I will ask (if possible) if such shifts happen that it would stick around longer instead of flashing for a split second. that would not only make it more comfortable but give the user a chance to look at it for a few more seconds 
(IMO, if it had some sort of "Fade out" thing like etherni dodge 2's feather bar option to "fade out of render" when full, that would be a nice quality effect)

Thanks for taking your time to read this, and I do apologize for any inconvenience or time that I might have wasted with you. the mod overall is still new to me and it's very interesting.

(and you might have dodged a bullet, EFM has been known to break other mods in unexpected ways, take Nyar's quivers mod, EFMs methods seem to break the HUD element for the quiver)

Thanks again and let me know your thoughts about the pose bar sticking around for a few seconds longer (and if adding a fade to it to make it smooth looking). I'll be here, and thanks again for your time.
