### ISSUE TITLE
1.16.5 configuration question

### ISSUE THREAD

**Issue by SteamDoge9000** [Jackiecrazy/WarDance#48]
Ive noticed that if I clear the detection list, it might make the mobs break for some reason

I'm not sure if this is a valid issue but this was done to try and disable the custom stealth observation system. while I appreciate the detail, I do find it a bit annoying at times when being done with things like player grinding a vindicator spawner. if this is an issue and someone wants to disble them all without breaking the ai, maybe some system that would either disable it like a config option to turn the system on and off, or have it check if its on the list and if its not then it would assume it would run default AI detection settings.

**Comment by Jackiecrazy** [comment]
I don't understand what you mean by breaking mobs. Deleting every entry will make every mob obey the custom stealth system. There is indeed an option to disable the stealth system in its entirety. The AI detection is not modified in any way, I merely reduce detection distance like vanilla mob heads and sneaking would.

**Comment by SteamDoge9000** [comment]
Oh what's the name of this option

**Comment by Jackiecrazy** [comment]
It's at the top of stealth.toml:
``
#enable or disable the entire system
"enable stabbing" = true
``

**Comment by SteamDoge9000** [comment]
oh, thats a bit misleading, did not think that was the master switch
thanks

**Comment by SteamDoge9000** [comment]
I thought it was an entirely different system altogether that was referring to
