### ISSUE TITLE
Compatibility Issue: The player shield parries their own spartan weaponry boomerangs when retrieving it

### ISSUE THREAD

**Issue by RecyclingTiger** [Jackiecrazy/WarDance#49]
With a shield in the offhand (and not blocking), after throwing any spartan weaponry boomerang, when the boomerang comes back, it briefly bounces off the player making it harder to retrieve.
Luckily this is easy to avoid by just not holding a shield, but it is slightly inconvenient.

**Comment by Jackiecrazy** [comment]
This should be fixed as of the latest release.
