### ISSUE TITLE
[Minor Bug] Gui offset w/ ConsoleExperience

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#5]
**Context:** I use a variety of mods in my mod-pack and one of them is called [Console Experience](https://www.curseforge.com/minecraft/mc-mods/console-hud). It's a minor mod that modifys Minecraft's HUD to look like the days when bedrock edition was backed by 4J Studios.

Issue: The Wardance exhaustion bar, _(not sure what to call it, sorry lol)_ is unadjusted with the GUI.
![Screenshot (97)](https://user-images.githubusercontent.com/69068153/108658759-2c2a1480-7490-11eb-9f1d-2a620346ae4f.png)
_(the blue feathers are from Elanaidodge.)_

It's a common issue with this mod similarly to Elenaidodge -> [Issue](https://github.com/ElenaiDev/ElenaiDodge2.0/issues/12)

**Comment by Cixon** [comment]
Also the ball in the middle is from a mod called SurvivalOverhaul lol

**Comment by Jackiecrazy** [comment]
Hm. Do the client configs not work?

**Comment by Cixon** [comment]
I didn't know that Wardance has this! I'll try it out.

**Comment by Cixon** [comment]
![Screenshot (98)](https://user-images.githubusercontent.com/69068153/108742158-0b4bd880-74fd-11eb-87ad-3c165a5cd5b7.png)

Yes the wardance-client.toml works!
**Suggestion;** Add a configuration in settings to optimize positioning in real-time!
