### ISSUE TITLE
改善潜行系统图像的显示

### ISSUE THREAD

**Issue by XiFengXF** [Jackiecrazy/WarDance#50]
潜行系统的图像过多了影响画面，能否改为一定范围内显示，并且加入黑名单来取消部分生物无法显示该潜行图像，因为太多小生物确实很影响画面且无用
PS:更新了图像和潜行系统确实棒极了，希望修复上面问题来适配我的整合包，只不过说实话，仍然考虑盾牌可以抵挡伤害，但是会减架势值这个修改吗？我的整合包：https://www.mcbbs.net/forum.php?mod=viewthread&tid=1311451&page=1&extra=#pid24880541
希望战舞计划能在里边大放光彩

**Comment by Jackiecrazy** [comment]
害，我MCBBS帐号丢了。
的确有黑名单。不需要潜行系统的生物在stealth.toml里面定义为mv即可使其永久处于警惕状态，因为警惕状态没有潜行图像，这个生物除了特殊状态（石化睡眠麻痹分心混乱窒息掠影干癣）都不会显示潜行。

**Comment by XiFengXF** [comment]
这个是过期的整合包演示 https://www.bilibili.com/video/BV1L5411f7Qx?spm_id_from=333.999.0.0 （难道我帖子过期了？），主要有一个问题是攻击一个生物会导致附加所以区块内的生物穿透方块显示潜行图像，导致满屏幕都密密麻麻的，所以才想一定范围内的生物才允许显示，或者说看得到的生物才可以显示？但估计很悬

**Comment by Jackiecrazy** [comment]
有点长，能给个时间吗？我写的潜行图标应该是不穿方块的啊？

**Comment by XiFengXF** [comment]
加了BSL光影的情况下确实如此，不过可能是opfine那个性能选项全开的原因，
这个短点的https://www.bilibili.com/video/BV1ou411Q7Er/?spm_id_from=333.788.recommend_more_video.0

**Comment by XiFengXF** [comment]
![2022-03-27_08 27 42](https://user-images.githubusercontent.com/97110012/160261493-5d12f6a2-7e5f-4cad-a459-aa6b34f84107.png)

**Comment by XiFengXF** [comment]
在无高清修复性能的情况下也是如此

**Comment by Jackiecrazy** [comment]
![2022-03-27_15 20 06](https://user-images.githubusercontent.com/6895485/160271151-e55d3a5b-02af-4893-b00f-01ffd03fa9c3.png)
无其他模组的情况下无法重现此问题。

**Comment by XiFengXF** [comment]
em，是不是不兼容其他模组的方块

**Comment by Jackiecrazy** [comment]
![2022-03-28_07 50 11](https://user-images.githubusercontent.com/6895485/160306533-6b52f205-f2c6-45f3-b53b-58dba4713b31.png)
再打多少次都没有。只有被渲染的生物才会渲染潜行图标，请确定有没有其他模组修改渲染判定。

**Comment by Jackiecrazy** [comment]
成功重现出问题了，大概率是某个其他模组作怪，总之我先试着修一下。

**Comment by XiFengXF** [comment]
已解决，发现问题模组为： https://www.curseforge.com/minecraft/mc-mods/improved-mobs 应该与修改了怪物有几率透视有关，在配置文件中修改即可，类似修改生物透视的也会导致以上问题

**Comment by Jackiecrazy** [comment]
> 害，我MCBBS帐号丢了。 的确有黑名单。不需要潜行系统的生物在stealth.toml里面定义为mv即可使其永久处于警惕状态，因为警惕状态没有潜行图像，这个生物除了特殊状态（石化睡眠麻痹分心混乱窒息掠影干癣）都不会显示潜行。 

潜行图片黑名单已经存在了。特定模组的小动物有图片是因为没有加入默认配置，这个会加上。我正在整武打圆圈还有备考，所以最近不是特别有时间碰战舞计划。还有我很想念御灵的武器，有可能也会提上日程。
