### ISSUE TITLE
Bug - Mobs are not able to heal at times with potion effects

### ISSUE THREAD

**Issue by crafting-Aaron** [Jackiecrazy/WarDance#51]
For some reason, when using potions such as Instant Healing or Regeneration, a mob may not heal their health back. This also means villagers low on health will not heal whenever they level up in their profession as they would receive a small regeneration effect but nothing happens. When it comes to the undead, potions of harming may not work either. Other means of healing, like feeding pets, will still work as normal.

With testing, this may be temporarily fixed by exiting the world and rejoining but will not when using /reload

the problem will still return on a different villager or cow. Usually a newly spawned mob would have this bug. I have a big mod list but I believe this may be the mod that is causing this. I removed a couple mods and the moment I added this one, the problem came back. Let me know if posting my modlist is needed.

**Comment by Jackiecrazy** [comment]
This is likely due to the wounding mechanic. You can turn it off in the config by setting wounding scaling to 0.

**Comment by crafting-Aaron** [comment]
I do not see an option on the config files for this other than:
`#this percentage of incoming damage before armor is also added to wounding
#Range: 0.0 ~ 1.0
"wound percentage" = 0.0`
at the resources.toml
Is that the right one?
That still did not change the problem. Slashed a cow with a sword, waited a couple of minutes, and potions still don't work.

Also how does wounding work on a mob? I see that I can recover when sleeping but how would a mob like a companion be able to recover?

**Comment by Jackiecrazy** [comment]
That would be the option, yes. If it doesn't change the problem, then it's probably not wounding. Currently you can blacklist specific mobs from receiving wounding via the config.

**Comment by crafting-Aaron** [comment]
I tried experimenting with /data and /attribute
I can see that with 

> /attribute entity [entityid] minecraft:generic.max_health get
It does show a max health of 10 but when I check with

> /data get entity [entityid]
It shows the attribute as base 0.0b
If I modify the attribute through /data it fixes it and now I can heal the cow. This is really strange.

**Comment by crafting-Aaron** [comment]
Also thank you for the command suggestion! It gave me a lead as to what was causing this. But the problem still stands as to why the attribute changes when attacking an entity.

**Comment by Jackiecrazy** [comment]
Hrm. I don't think that's me; maybe some other mod is doing bad things behind the scenes, and I'm just the one to make it manifest. Does changing the config do anything?

**Comment by Jackiecrazy** [comment]
Had no input on this. Assuming it's fixed.
