### ISSUE TITLE
Error when connecting to a server

### ISSUE THREAD

**Issue by FebKB** [Jackiecrazy/WarDance#52]
I recently tried to use Project: War Dance for a heavily modded modpack, it works fine in singleplayer despite the 245 mods I use, but for some reason when I try to use it on a server, it doesn't work. The server works fine, it's on the player's end that the connection fails because something doesn't load. The error in question is -> Internal exception: io.netty.handler.codec.EncoderException:java.lang.NullPointerException.
When looking on the server's lines it says this specifically: Could not serialize jackiecrazy.wardance.command.SkillArgument@12035f1c (class jackiecrazy.wardance.command.SkillArgument) - will not be sent to client.
Please tell me what's wrong, I don't know what it means and I would like to keep this combat system. It's not obnoxiously different like Epic fight, but it's also not too simple like Parry this!. I'd love to hear if there is a fix to this, because I will utilise it as soon as possible.

**Comment by Jackiecrazy** [comment]
Is this on a special server type (magma, mohist, etc.)? I remember playing on a "vanilla" forge server with this installed.

**Comment by Jackiecrazy** [comment]
Had no input on this. Assuming it's fixed.

**Comment by FebKB** [comment]
I am so sorry for not answering, I ocmpletely foegot about it
