### ISSUE TITLE
wardance-0.8.8-hotfix 启动直接崩溃

### ISSUE THREAD

**Issue by XiFengXF** [Jackiecrazy/WarDance#54]
更新后开启自己的整合包直接崩溃了，然后发现是这个的问题;之后单独拎出来加载时仍然崩溃，这是错误报告
[错误报告-2022-8-26_11.10.53.zip](https://github.com/Jackiecrazy/WarDance/files/9429490/-2022-8-26_11.10.53.zip)

**Comment by Jackiecrazy** [comment]
刚刚修好了。如果无所谓潜行系统的话这个版本和之前的那一个是一样的。

**Comment by XiFengXF** [comment]
行，辛苦了~
