### ISSUE TITLE
Serverside Forge 1.19.2 FML Crash

### ISSUE THREAD

**Issue by KK1ve** [Jackiecrazy/WarDance#58]
Forge version:1.19.2-43.2.8
Mod version:attributizer-1.1.jar, footwork-2.2.jar, wardance-1.0.3.jar

[crash-2023-03-30_13.39.52-fml.txt](https://github.com/Jackiecrazy/WarDance/files/11108166/crash-2023-03-30_13.39.52-fml.txt)
[debug.log](https://github.com/Jackiecrazy/WarDance/files/11108167/debug.log)
[latest.log](https://github.com/Jackiecrazy/WarDance/files/11108168/latest.log)

**Comment by Jackiecrazy** [comment]
Fixed as of the latest version.
