### ISSUE TITLE
Multiplayer incompatibility 

### ISSUE THREAD

**Issue by Mordunce** [Jackiecrazy/WarDance#60]
Hello, I'm using Project Wardance version 1.4.0 for 1.19.2 and it always crashes inside the server. It works just fine single player, but if placed inside a server it will prevent it from starting making it multiplayer incompatible.

[crash-2023-08-20_16.46.58-fml.txt](https://github.com/Jackiecrazy/WarDance/files/12388684/crash-2023-08-20_16.46.58-fml.txt)

**Comment by Jackiecrazy** [comment]
This has been fixed and the new version is uploading.
