### ISSUE TITLE
(1.20.1) PWD not working on newer Forge versions

### ISSUE THREAD

**Issue by BugmanBugman** [Jackiecrazy/WarDance#63]
Been trying to add this to my pack for a while but been unable to due to a hard coded limit. Sucks because I can't downgrade either without losing mods meant for newer versions of forge. Anyway so it can be used for 47.2.0 and up?

**Comment by Jackiecrazy** [comment]
2.1.3 is compiled against a higher version of forge. Using 2.1.4+ in a higher version of forge causes projectile parries to crash. There is nothing I can do about this, as higher versions of lexforge include various dubious refactors.
