### ISSUE TITLE
关于实体交互距离的疑问

### ISSUE THREAD

**Issue by masonclomid** [Jackiecrazy/WarDance#67]
在战舞1.16最新版本中，玩家对实体的攻击距离好像过于远了。
在原版里以创造模式为例，玩家有方块触及距离5格和实体交互距离3格，对实体的攻击和交互均为3格，但加了战舞后，对实体交互距离仍3格，但持械攻击能达到5格甚至更远一点，哪怕空手减1格也比3格远。同时攻击距离好像绑定到触及距离上了而且随其改变。请问这是某个配置导致的吗，能够改回原版状态吗？或者如果可以的话能不能给1.16更新一个攻击距离配置？
另外战舞1.16视死如归技能里像亡语的受致命伤免疫效果5秒好像没生效，致命了就直接死了，这是正常的吗？

**Comment by Jackiecrazy** [comment]
1.16没有攻击范围属性，只能使用方块距离属性导致实际距离比游戏内攻击距离远一点。
1.16版本已经停更，不增加新内容、不修改已存在内容。以后我一时兴起想回去玩1.16有可能重新开始更新，概率不高。
须臾之念需要装备后睡觉刷新才能使用。
