### ISSUE TITLE
Entities with the Invulnerable NBT tag take damage.

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#7]
**Context:** I have NPCs in my server and I noticed they take damage even tho they aren't allowed to due to their unique tag.
The NBT tag is suppose to make them immune to every incoming attack no matter the circumstances unless a player is in creative mode.

I'd love if this can be fixed!

**Comment by Jackiecrazy** [comment]
I can't seem to replicate this; an invulnerable zombie on my end doesn't take damage unless I'm in creative mode, either. Could some other mod be interfering?

**Comment by Cixon** [comment]
Hmm, this is so bizarre. Not sure what the hell happened. I added a small handful of mods including yours so I assumed it was yours, what really happened was one of the mods in the group disabled the invulnerability NBT tag after installation.

I will do deeper investigating, sorry for possibly false reporting.

**Comment by Cixon** [comment]
I was using my fist in survival mode btw.

**Comment by Jackiecrazy** [comment]
No problem. Better report a potential issue than let it go unnoticed and eventually detonate into something gamebreaking.
