### ISSUE TITLE
[Suggestion/Issue] How Potion effects affect Wounding mechanic.

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#8]
**Context:** So I use a mod similar to ToughAsNails called [Survival Overhaul](https://www.curseforge.com/minecraft/mc-mods/survival-overhaul). This mod adds a temperature system to Minecraft so players need to be careful when entering hot / cold environments.

**Issue:** If players are in extreme conditions, they will get either the Heat Stroke, or Frostbite potion effect, depending on the temperatures.

Wardance considers this into it's Wounding mechanic which my server users and I don't prefer.
I'd rather have Wounding only consider mob/player damage, fall damage, arrows, and stuff like that.
Only potion that would make sense to me would be potion of instant damage but I'm going on a tangent here lol.

**Suggestion:** Add a option in config to disable potion effects from affecting Wardance's wounding mechanic.

This is all!
Thank you and great mod!
Best Regards,
Cixon.

**Comment by Jackiecrazy** [comment]
Done! There is now a configurable list of damage sources that either don't add wounding or are the only ones allowed to add wounding. Expect a release in a few hours.
