### ISSUE TITLE
[1.16.5] Wardance v0.2.4 Crash Startup - NoClassDefFoundError

### ISSUE THREAD

**Issue by Cixon** [Jackiecrazy/WarDance#9]
Not much to say here but uh, yeah.
I'm tried using the latest Wardance mod with my 36.0.42 Forge server.
It wouldn't let me, I guess there's something you forgot to include? ;

[crash-2021-03-03_01.28.44-fml.txt](https://github.com/Jackiecrazy/WarDance/files/6074284/crash-2021-03-03_01.28.44-fml.txt)
[latest.log](https://github.com/Jackiecrazy/WarDance/files/6074282/latest.log)
[debug.log](https://github.com/Jackiecrazy/WarDance/files/6074283/debug.log)

**Comment by Jackiecrazy** [comment]
oops, yeah, I forgot to make tooltips client only. Fixed version is currently uploading.
